import os, sys      # This boilerplate is just for the tests, since the script is placed in a parent directory
sys.path.insert(1, os.path.dirname(os.getcwd()))

import bashr as b

def script():
    b.clear()
    b.echo("Terminal cleared.")
    b.echo()
    b.echo("Hello World!")
    b.echo(b.Echo.Strike + "Strikethrough")
    b.echo("Bold: " + b.Echo.Bold + "test")
    b.echo("Dim: " + b.Echo.Dim + "test")
    b.echo("Underline: " + b.Echo.Underline + "test")
    b.echo("Italic: " + b.Echo.Italic + "test")
    b.echo("Invert: " + b.Echo.Bold + "test")
    b.echo("Hidden: " + b.Echo.Hidden + "test")
    b.echo("This is a \"Quote\" test")
    b.echo("Do not show me!") > b.null_sink()
    b.echo()

    b.set_var("var1", 50)
    b.echo(f'var1 = {b.get_var("var1")}')
    b.set_var("var2", 48)
    b.echo(f'var2 = {b.get_var("var2")}')
    b.set_var("var3", 48)
    b.echo(f'var3 = {b.get_var("var3")}')
    b.set_var("var4", -5)
    b.echo(f'var4 = {b.get_var("var4")}')
    b.echo()

    b.set_var("result", b.if_inline(b.eq(b.get_var("var1"), b.get_var("var2")), b.echo("Right"), b.echo("Wrong")))
    b.echo(f'var1 == var2: {b.get_var("result")}')
    b.set_var("result", b.if_inline(b.eq(b.get_var("var2"), b.get_var("var3")), b.echo("Right"), b.echo("Wrong")))
    b.echo(f'var2 == var3: {b.get_var("result")}')
    b.set_var("result", b.if_inline(b.ne(b.get_var("var1"), b.get_var("var2")), b.echo("Right"), b.echo("Wrong")))
    b.echo(f'var1 != var2: {b.get_var("result")}')
    b.set_var("result", b.if_inline(b.ne(b.get_var("var2"), b.get_var("var3")), b.echo("Right"), b.echo("Wrong")))
    b.echo(f'var2 != var3: {b.get_var("result")}')
    
    b.echo()
    b.set_var("result", b.if_inline(b.gt(b.get_var("var4"), b.get_var("var1")), b.echo("Right"), b.echo("Wrong")))
    b.echo(f'var4 > var1: {b.get_var("result")}')
    b.set_var("result", b.if_inline(b.gt(b.get_var("var1"), b.get_var("var2")), b.echo("Right"), b.echo("Wrong")))
    b.echo(f'var1 > var2: {b.get_var("result")}')
    b.set_var("result", b.if_inline(b.ge(b.get_var("var2"), b.get_var("var3")), b.echo("Right"), b.echo("Wrong")))
    b.echo(f'var2 >= var3: {b.get_var("result")}')
    b.set_var("result", b.if_inline(b.ge(b.get_var("var4"), b.get_var("var3")), b.echo("Right"), b.echo("Wrong")))
    b.echo(f'var4 >= var3: {b.get_var("result")}')
    b.set_var("result", b.if_inline(b.lt(b.get_var("var4"), b.get_var("var1")), b.echo("Right"), b.echo("Wrong")))
    b.echo(f'var4 < var1: {b.get_var("result")}')
    b.set_var("result", b.if_inline(b.lt(b.get_var("var1"), b.get_var("var2")), b.echo("Right"), b.echo("Wrong")))
    b.echo(f'var1 < var2: {b.get_var("result")}')
    b.set_var("result", b.if_inline(b.le(b.get_var("var2"), b.get_var("var3")), b.echo("Right"), b.echo("Wrong")))
    b.echo(f'var2 <= var3: {b.get_var("result")}')
    b.set_var("result", b.if_inline(b.le(b.get_var("var4"), b.get_var("var3")), b.echo("Right"), b.echo("Wrong")))
    b.echo(f'var4 <= var3: {b.get_var("result")}')

b.generate(script)

# file = "out/test.txt"
# b.echo()
# b.echo(f"Touching {file}...")
# b.touch(file)
# b.echo(f"Done")